- action:
  - action: eud4xr.deactivates
    data:
      entity_id: sensor.cube1_ecaobject
  alias: Rule 1
  condition: []
  description: When the player pushes the button, cube1 deactivates.
  id: '202412311011570000'
  trigger:
  - event_data:
      obj: pulsante
      subject: player
      verb: pushes
    event_type: eud4xr
    platform: event
