- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_lanascitadivenere_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino alla nascita di venere
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a30
  trigger:
  - event_data:
      obj: quadro_lanascitadivenere
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_rondadinotte_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino alla ronda di notte
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a31
  trigger:
  - event_data:
      obj: quadro_rondadinotte
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_ophelia_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino al quadro di Ophelia
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a32
  trigger:
  - event_data:
      obj: quadro_ophelia
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_lazatteradellamedusa_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino al quadro la zattera della medusa
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a33
  trigger:
  - event_data:
      obj: quadro_lazatteradellamedusa
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_colazionesullerba_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino al quadro la colazione sull'erba
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a34
  trigger:
  - event_data:
      obj: quadro_colazionesullerba
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.faretto_primavera_ecalight
      newStatus: 'on'
  alias: Accendi il faretto quando mi avvicino al quadro la primavera
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a35
  trigger:
  - event_data:
      obj: quadro_primavera
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event


- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_lanascitadivenere_ecaobject
  alias: Mostra il pannello descrittivo quando mi avvicino alla nascita di venere
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a36
  trigger:
  - event_data:
      obj: quadro_lanascitadivenere
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_rondadinotte_ecaobject
  alias: Mostra il pannellodescrizione quando mi avvicino alla ronda di notte
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a37
  trigger:
  - event_data:
      obj: quadro_rondadinotte
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_ophelia_ecaobject
  alias: Mostra il pannellodescrizione quando mi avvicino al quadro di Ophelia
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a38
  trigger:
  - event_data:
      obj: quadro_ophelia
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_lazatteradellamedusa_ecaobject
  alias: Mostra il pannellodescrizione quando mi avvicino al quadro la zattera della medusa
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a39
  trigger:
  - event_data:
      obj: quadro_lazatteradellamedusa
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_colazionesullerba_ecaobject
  alias: Mostra il pannellodescrizione quando mi avvicino al quadro la colazione sull'erba
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a40
  trigger:
  - event_data:
      obj: quadro_colazionesullerba
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event

- action:
  - action: eud4xr.shows
    data:
      entity_id: sensor.pannellodescrizione_primavera_ecaobject
  alias: Mostra il pannellodescrizione quando mi avvicino al quadro la primavera
  condition: []
  description: ''
  id: 3694bc70-5dc8-46cd-adaa-64b2aa058a41
  trigger:
  - event_data:
      obj: quadro_primavera
      subject: player
      verb: interacts with
    event_type: eud4xr
    platform: event