- action:
  - action: eud4xr.turns
    data:
      entity_id: sensor.luce_ecalight
      newStatus: 'off'
  alias: Spegni la luce quando il cubo 1 si trova nella posizione 0,1,0
  condition: []
  description: ''
  id: '10000000000000000001'
  trigger:
  - event_data:
      obj:
        x: 0
        y: 1
        z: 0
      subject: cube1
      verb: moves to
    event_type: eud4xr
