# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
#script: !include scripts.yaml
#scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug
    custom_components.eud4xr: debug

# debugpy:
#   start: true
#wait: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.1

eud4xr:
  server_unity_url: "YOUR-UNITY-URL:8080"
  server_unity_token: "token" # non cancellare ma da non modificare
  # scopa
  unity_entities:
    - eca_script: "ECAObject"
      game_object: "Scopa@ECAObject"
      unity_id: "Scopa@ECAObject"
      attributes: {
        "position": {'x': 1, 'y': 1, 'z': 1},
        "rotation": {'x': 0, 'y': -90, 'z': 0},
        "scale": {'x': 1, 'y': 1, 'z': 1},
        "visible": "yes",
        "active": "yes",
        "isInsideCamera": "yes",
        "description": "oggetto per pulire il pavimento",
      }
    - eca_script: "ECACleaningItem"
      game_object: "Scopa@ECACleaningItem"
      unity_id: "Scopa@ECACleaningItem"
    - eca_script: "ECABroom"
      game_object: "Scopa@ECABroom"
      unity_id: "Scopa@ECABroom"
    - eca_script: "ECAProp"
      game_object: "Scopa@ECAProp"
      unity_id: "Scopa@ECAProp"
      attributes: {
        "price": 0.0
      }
    # spruzzino
    - eca_script: "ECAObject"
      game_object: "Spruzzino@ECAObject"
      unity_id: "Spruzzino@ECAObject"
      attributes: {
        "position": {'x': 5, 'y': 1, 'z': 1},
        "rotation": {'x': 0, 'y': 0, 'z': 0},
        "scale": {'x': 1, 'y': 1, 'z': 1},
        "visible": "yes",
        "active": "yes",
        "isInsideCamera": "yes",
        "description": "oggetto che emette liquidi che possono essere assorbiti da stracci, mocci o secchi.",
      }
    - eca_script: "ECASprayBottle"
      game_object: "Spruzzino@ECASprayBottle"
      unity_id: "Spruzzino@ECASprayBottle"
    - eca_script: "ECALiquidDispenser"
      game_object: "Spruzzino@ECALiquidDispenser"
      unity_id: "Spruzzino@ECALiquidDispenser"
      attributes: {
        "liquidType": "water"
      }
    - eca_script: "ECAProp"
      game_object: "Spruzzino@ECAProp"
      unity_id: "Spruzzino@ECAProp"
      attributes: {
        "price": 0.0
      }
    # secchio
    - eca_script: "ECAObject"
      game_object: "Secchio@ECAObject"
      unity_id: "Secchio@ECAObject"
      attributes: {
        "position": {'x': -5, 'y': 1, 'z': 1},
        "rotation": {'x': 0, 'y': 0, 'z': 0},
        "scale": {'x': 1, 'y': 1, 'z': 1},
        "visible": "yes",
        "active": "yes",
        "isInsideCamera": "yes",
        "description": "oggetto che contiene dei liquidi.",
      }
    - eca_script: "ECABucket"
      game_object: "Secchio@ECABucket"
      unity_id: "Secchio@ECABucket"
    - eca_script: "ECALiquidContainer"
      game_object: "Secchio@ECALiquidContainer"
      unity_id: "Secchio@ECALiquidContainer"
      attributes: {
        "waterDrops": 1000,
        "degreaserDrops": 1000,
        "batteryKillerDrops": 1000,
        "amuchinaDrops": 1000,
        "temperature": 30.5
      }
    - eca_script: "ECAProp"
      game_object: "Secchio@ECAProp"
      unity_id: "Secchio@ECAProp"
      attributes: {
        "price": 0.0
      }
    # tavolo
    - eca_script: "ECAObject"
      game_object: "Tavolo@ECAObject"
      unity_id: "Tavolo@ECAObject"
      attributes: {
        "position": {'x': 1, 'y': 1, 'z': -5},
        "rotation": {'x': 0, 'y': 0, 'z': 0},
        "scale": {'x': 1, 'y': 1, 'z': 1},
        "visible": "yes",
        "active": "yes",
        "isInsideCamera": "yes",
        "description": "superficie di lavoro.",
      }
    - eca_script: "ECAEnvironment"
      game_object: "Tavolo@ECAEnvironment"
      unity_id: "Tavolo@ECAEnvironment"
    - eca_script: "ECASurface"
      game_object: "Tavolo@ECASurface"
      unity_id: "Tavolo@ECASurface"
      attributes: {
        "type": "tavolo di legno"
      }
    - eca_script: "ECADustBall"
      game_object: "Tavolo@ECADustBall"
      unity_id: "Tavolo@ECADustBall"
      attributes: {
        "sweepsCounter": 1,
        "allSwept": "false"
      }
    - eca_script: "ECAOilStain"
      game_object: "Tavolo@ECAOilStain"
      unity_id: "Tavolo@ECAOilStain"
      attributes: {
        "washesCounter": 1,
        "allWashed": "false"
      }
    # player
    - eca_script: "ECAObject"
      game_object: "Player@ECAObject"
      unity_id: "Player@ECAObject"
      attributes: {
        "position": {'x': 0, 'y': 0, 'z': -15},
        "rotation": {'x': 0, 'y': 0, 'z': 0},
        "scale": {'x': 1, 'y': 1, 'z': 1},
        "visible": "yes",
        "active": "yes",
        "isInsideCamera": "no",
        "description": "utente che ha il visore.",
      }
    - eca_script: "ECACharacter"
      game_object: "Player@ECACharacter"
      unity_id: "Player@ECACharacter"
      attributes: {
        "life": 100,
        "playing": "yes",
      }
    - eca_script: "ECAAnimal"
      game_object: "Player@ECAAnimal"
      unity_id: "Player@ECAAnimal"
    - eca_script: "ECAHuman"
      game_object: "Player@ECAHuman"
      unity_id: "Player@ECAHuman"

group:
  scopa:
   name: "scopa"
   entities:
    - sensor.scopa_ecaobject
    - sensor.scopa_ecacleaningitem
    - sensor.scopa_ecabroom
    - sensor.scopa_ecaprop
  spruzzino:
   name: "spruzzino"
   entities:
    - sensor.spruzzino_ecaobject
    - sensor.spruzzino_ecaprop
    - sensor.spruzzino_ecaliquiddispenser
    - sensor.spruzzino_ecaspraybottle
  secchio:
   name: "secchio"
   entities:
    - sensor.secchio_ecaobject
    - sensor.secchio_ecaprop
    - sensor.secchio_ecaliquidcontainer
    - sensor.secchio_ecabucket
  tavolo:
   name: "tavolo"
   entities:
    - sensor.tavolo_ecaobject
    - sensor.tavolo_ecaenvironment
    - sensor.tavolo_ecasurface
    - sensor.tavolo_ecadustball
    - sensor.tavolo_ecaoilstain
  player:
   name: "player"
   entities:
    - sensor.player_ecaobject
    - sensor.player_ecacharacter
    - sensor.player_ecaanimal
    - sensor.player_ecahuman
